# Generated by Django 5.2.3 on 2025-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, default=None, help_text='Passage ID', max_length=255, null=True, unique=True, verbose_name='passage_id'),
        ),
    ]
