# Generated by Django 5.2.3 on 2025-10-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('finalizado', False)), fields=('usuario',), name='unique_carrinho_ativo_por_usuario'),
        ),
    ]
