# Generated by Django 5.2.3 on 2025-09-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria'),
        ),
    ]
